# Generated by Django 4.1.1 on 2023-04-18 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='Title',
            new_name='title',
        ),
    ]
